### ISSUE TITLE
1- Venta Detalle

### ISSUE THREAD

**Issue by gumaterror** [gumaterror/is42018#29]
1- Antes de agregar una venta detalle a una venta, verificar que el estado de la VENTA sea estado disponible.
Sino emitir un mensaje de error de tipo Excepcion con codigo de error HTTP

**Comment by gumaterror** [comment]
Agregar codigo de error HTTP de tipo excepcion en todos los mensajes en caso de error de algun tipo, ejemplo error de validacion

**Comment by Damian511** [comment]
Buenas Prof. me podes pasar la información de como enviar los códigos de excepción HTTP  no estoy pudiendo encontrar.

**Comment by gumaterror** [comment]
Correcto
